@startuml
skinparam dpi 200

actor User

participant ProductRestController
participant ProductService
participant ProductMapper
participant RestHelper
database Database

User -> ProductRestController: getProductListByType2()
ProductRestController -> ProductService: getItemListByType2()
ProductService -> ProductMapper: selectListByType2()
ProductMapper -> Database
Database --> ProductMapper
ProductMapper --> ProductService
ProductService --> ProductRestController
ProductRestController -> RestHelper: sendJson()
RestHelper --> ProductRestController
ProductRestController --> User
User -> ProductRestController: getProductListByType3()
ProductRestController -> ProductService: getItemListByType3()
ProductService -> ProductMapper: selectListByType3()
ProductMapper -> Database
Database --> ProductMapper
ProductMapper --> ProductService
ProductService --> ProductRestController
ProductRestController -> RestHelper: sendJson()
RestHelper --> ProductRestController
ProductRestController --> User

@enduml