@startuml
skinparam dpi 200

actor User

User -> ProductRestController : getProductListByType2(String type, String type2)
activate ProductRestController

ProductRestController -> ProductService : getProductListByType2(String type, String type2)
activate ProductService

ProductService -> ProductMapper : selectProductsByType2(String type, String type2)
activate ProductMapper
ProductMapper -> Database : SELECT * FROM products WHERE type = #{type} AND type2 = #{type2}
deactivate ProductMapper

ProductService -> ProductRestController : List<Product>
deactivate ProductService

ProductRestController -> User : List<Product>
deactivate ProductRestController

@enduml